scrape_configs:
  - job_name: monolith
    scrape_interval: 20s
    static_configs:
      - targets:
          - monolith:8080
    basic_auth:
      username: ""
      password: MySuperSecretCode
    enable_http2: false